# Site settings
title: bloog
email: ryan.joshua.jones@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A wonderful bloog.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://polyrhythm.github.io" # the base hostname & protocol for your site
twitter_username: polyrhytmical
github_username:  polyrhythm

# Build settings
markdown: kramdown
